/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crypto;


import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.ImageCursor;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author Duc Nguyen Van
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }
    
    /**
     * Variables
     */
    public JFileChooser chooseFile = new JFileChooser();
    public JFileChooser chooseDirectory = new JFileChooser();
    public File inputFile;
    public String inputFilePath;
    public File key;
    public String keyPath;
    public File encryptedFile;
    public File decryptedFile;
    public String encryptedFilePath;
    public File resultFolder;
    public String resultFolderPath;
    private Component frame;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        filePanel = new javax.swing.JPanel();
        btnClear1 = new javax.swing.JButton();
        btnStart1 = new javax.swing.JButton();
        radioEncrypt1 = new javax.swing.JRadioButton();
        radioDecrypt1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtFilePath1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboCryptType1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtKeyPath1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtResultFolder1 = new javax.swing.JTextField();
        btnFile1 = new javax.swing.JButton();
        btnKey1 = new javax.swing.JButton();
        btnResultFolder1 = new javax.swing.JButton();
        folderPanel = new javax.swing.JPanel();
        btnClear2 = new javax.swing.JButton();
        btnStart2 = new javax.swing.JButton();
        radioEncrypt2 = new javax.swing.JRadioButton();
        radioDecrypt2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtFilePath2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboCryptType2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtKeyPath2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtResultFolder2 = new javax.swing.JTextField();
        btnFile2 = new javax.swing.JButton();
        btnKey2 = new javax.swing.JButton();
        btnResultFolder2 = new javax.swing.JButton();
        checkPanel = new javax.swing.JPanel();
        btnClear3 = new javax.swing.JButton();
        btnStart3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtOriginalFilePath = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEncryptedFilePath = new javax.swing.JTextField();
        btnOriginalFile = new javax.swing.JButton();
        btnEncryptedFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Nb.Desktop.background"));
        setResizable(false);

        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);

        jProgressBar1.setBackground(new java.awt.Color(33, 120, 255));
        jProgressBar1.setForeground(new java.awt.Color(33, 120, 255));
        jProgressBar1.setMaximumSize(new java.awt.Dimension(580, 17));
        jProgressBar1.setMinimumSize(new java.awt.Dimension(580, 17));
        jProgressBar1.setPreferredSize(new java.awt.Dimension(580, 17));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Choose a file in the left-hand tab to start");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(33, 120, 255));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 0));

        jTabbedPane1.setBackground(new java.awt.Color(29, 155, 236));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setAlignmentX(0.0F);
        jTabbedPane1.setAlignmentY(0.0F);

        filePanel.setBackground(new java.awt.Color(33, 120, 255));

        btnClear1.setBackground(new java.awt.Color(29, 155, 236));
        btnClear1.setForeground(new java.awt.Color(255, 255, 255));
        btnClear1.setText("CLEAR");
        btnClear1.setToolTipText("");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        btnStart1.setBackground(new java.awt.Color(29, 155, 236));
        btnStart1.setForeground(new java.awt.Color(255, 255, 255));
        btnStart1.setText("START");
        btnStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioEncrypt1);
        radioEncrypt1.setForeground(new java.awt.Color(255, 255, 255));
        radioEncrypt1.setSelected(true);
        radioEncrypt1.setText("Encrypt");
        radioEncrypt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEncrypt1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioDecrypt1);
        radioDecrypt1.setForeground(new java.awt.Color(255, 255, 255));
        radioDecrypt1.setText("Decrypt");
        radioDecrypt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDecrypt1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("File to process");

        txtFilePath1.setBackground(new java.awt.Color(143, 218, 238));
        txtFilePath1.setMaximumSize(new java.awt.Dimension(234, 27));
        txtFilePath1.setMinimumSize(new java.awt.Dimension(234, 27));
        txtFilePath1.setPreferredSize(new java.awt.Dimension(234, 27));
        txtFilePath1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilePath1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cryptography type");

        comboCryptType1.setBackground(new java.awt.Color(29, 155, 236));
        comboCryptType1.setForeground(new java.awt.Color(255, 255, 255));
        comboCryptType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RSA", "DES", "AES" }));
        comboCryptType1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboCryptType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCryptType1ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Key file");

        txtKeyPath1.setBackground(new java.awt.Color(143, 218, 238));
        txtKeyPath1.setMaximumSize(new java.awt.Dimension(234, 27));
        txtKeyPath1.setMinimumSize(new java.awt.Dimension(234, 27));
        txtKeyPath1.setPreferredSize(new java.awt.Dimension(234, 27));
        txtKeyPath1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeyPath1ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Result folder");

        txtResultFolder1.setBackground(new java.awt.Color(143, 218, 238));
        txtResultFolder1.setMaximumSize(new java.awt.Dimension(234, 27));
        txtResultFolder1.setMinimumSize(new java.awt.Dimension(234, 27));
        txtResultFolder1.setPreferredSize(new java.awt.Dimension(234, 27));
        txtResultFolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultFolder1ActionPerformed(evt);
            }
        });

        btnFile1.setBackground(new java.awt.Color(29, 155, 236));
        btnFile1.setForeground(new java.awt.Color(255, 255, 255));
        btnFile1.setText("+");
        btnFile1.setMaximumSize(new java.awt.Dimension(41, 27));
        btnFile1.setMinimumSize(new java.awt.Dimension(41, 27));
        btnFile1.setPreferredSize(new java.awt.Dimension(41, 27));
        btnFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFile1ActionPerformed(evt);
            }
        });

        btnKey1.setBackground(new java.awt.Color(29, 155, 236));
        btnKey1.setForeground(new java.awt.Color(255, 255, 255));
        btnKey1.setText("+");
        btnKey1.setMaximumSize(new java.awt.Dimension(41, 27));
        btnKey1.setMinimumSize(new java.awt.Dimension(41, 27));
        btnKey1.setPreferredSize(new java.awt.Dimension(41, 27));
        btnKey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKey1ActionPerformed(evt);
            }
        });

        btnResultFolder1.setBackground(new java.awt.Color(29, 155, 236));
        btnResultFolder1.setForeground(new java.awt.Color(255, 255, 255));
        btnResultFolder1.setText("+");
        btnResultFolder1.setMaximumSize(new java.awt.Dimension(41, 27));
        btnResultFolder1.setMinimumSize(new java.awt.Dimension(41, 27));
        btnResultFolder1.setPreferredSize(new java.awt.Dimension(41, 27));
        btnResultFolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultFolder1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filePanelLayout = new javax.swing.GroupLayout(filePanel);
        filePanel.setLayout(filePanelLayout);
        filePanelLayout.setHorizontalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePanelLayout.createSequentialGroup()
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filePanelLayout.createSequentialGroup()
                        .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(filePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(filePanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(filePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboCryptType1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(filePanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(radioEncrypt1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioDecrypt1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(filePanelLayout.createSequentialGroup()
                                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(filePanelLayout.createSequentialGroup()
                                        .addComponent(txtFilePath1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(filePanelLayout.createSequentialGroup()
                                        .addComponent(txtResultFolder1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnResultFolder1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(filePanelLayout.createSequentialGroup()
                                        .addComponent(txtKeyPath1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        filePanelLayout.setVerticalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilePath1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCryptType1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioEncrypt1)
                    .addComponent(radioDecrypt1))
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeyPath1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResultFolder1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResultFolder1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear1)
                    .addComponent(btnStart1))
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("File", filePanel);

        folderPanel.setBackground(new java.awt.Color(33, 120, 255));
        folderPanel.setForeground(new java.awt.Color(255, 255, 255));

        btnClear2.setBackground(new java.awt.Color(29, 155, 236));
        btnClear2.setForeground(new java.awt.Color(255, 255, 255));
        btnClear2.setText("CLEAR");
        btnClear2.setToolTipText("");
        btnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear2ActionPerformed(evt);
            }
        });

        btnStart2.setBackground(new java.awt.Color(29, 155, 236));
        btnStart2.setForeground(new java.awt.Color(255, 255, 255));
        btnStart2.setText("START");
        btnStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioEncrypt2);
        radioEncrypt2.setForeground(new java.awt.Color(255, 255, 255));
        radioEncrypt2.setSelected(true);
        radioEncrypt2.setText("Encrypt");
        radioEncrypt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEncrypt2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioDecrypt2);
        radioDecrypt2.setForeground(new java.awt.Color(255, 255, 255));
        radioDecrypt2.setText("Decrypt");
        radioDecrypt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDecrypt2ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Folder to process");

        txtFilePath2.setBackground(new java.awt.Color(143, 218, 238));
        txtFilePath2.setMaximumSize(new java.awt.Dimension(234, 27));
        txtFilePath2.setMinimumSize(new java.awt.Dimension(234, 27));
        txtFilePath2.setPreferredSize(new java.awt.Dimension(234, 27));
        txtFilePath2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilePath2ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cryptography type");

        comboCryptType2.setForeground(new java.awt.Color(255, 255, 255));
        comboCryptType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RSA", "DES", "AES" }));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Key file");

        txtKeyPath2.setBackground(new java.awt.Color(143, 218, 238));
        txtKeyPath2.setMaximumSize(new java.awt.Dimension(234, 27));
        txtKeyPath2.setMinimumSize(new java.awt.Dimension(234, 27));
        txtKeyPath2.setPreferredSize(new java.awt.Dimension(234, 27));
        txtKeyPath2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeyPath2ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Result folder");

        txtResultFolder2.setBackground(new java.awt.Color(143, 218, 238));
        txtResultFolder2.setMaximumSize(new java.awt.Dimension(234, 27));
        txtResultFolder2.setMinimumSize(new java.awt.Dimension(234, 27));
        txtResultFolder2.setPreferredSize(new java.awt.Dimension(234, 27));
        txtResultFolder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultFolder2ActionPerformed(evt);
            }
        });

        btnFile2.setBackground(new java.awt.Color(29, 155, 236));
        btnFile2.setForeground(new java.awt.Color(255, 255, 255));
        btnFile2.setText("+");
        btnFile2.setMaximumSize(new java.awt.Dimension(41, 27));
        btnFile2.setMinimumSize(new java.awt.Dimension(41, 27));
        btnFile2.setPreferredSize(new java.awt.Dimension(41, 27));
        btnFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFile2ActionPerformed(evt);
            }
        });

        btnKey2.setBackground(new java.awt.Color(29, 155, 236));
        btnKey2.setForeground(new java.awt.Color(255, 255, 255));
        btnKey2.setText("+");
        btnKey2.setMaximumSize(new java.awt.Dimension(41, 27));
        btnKey2.setMinimumSize(new java.awt.Dimension(41, 27));
        btnKey2.setPreferredSize(new java.awt.Dimension(41, 27));
        btnKey2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKey2ActionPerformed(evt);
            }
        });

        btnResultFolder2.setBackground(new java.awt.Color(29, 155, 236));
        btnResultFolder2.setForeground(new java.awt.Color(255, 255, 255));
        btnResultFolder2.setText("+");
        btnResultFolder2.setMaximumSize(new java.awt.Dimension(41, 27));
        btnResultFolder2.setMinimumSize(new java.awt.Dimension(41, 27));
        btnResultFolder2.setPreferredSize(new java.awt.Dimension(41, 27));
        btnResultFolder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultFolder2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout folderPanelLayout = new javax.swing.GroupLayout(folderPanel);
        folderPanel.setLayout(folderPanelLayout);
        folderPanelLayout.setHorizontalGroup(
            folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(folderPanelLayout.createSequentialGroup()
                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(folderPanelLayout.createSequentialGroup()
                        .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(folderPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6))
                            .addGroup(folderPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnClear2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnStart2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(folderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboCryptType2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(folderPanelLayout.createSequentialGroup()
                                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtResultFolder2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKeyPath2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnKey2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnResultFolder2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(folderPanelLayout.createSequentialGroup()
                                .addComponent(txtFilePath2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, folderPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(radioEncrypt2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioDecrypt2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        folderPanelLayout.setVerticalGroup(
            folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, folderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilePath2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCryptType2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioEncrypt2)
                    .addComponent(radioDecrypt2))
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeyPath2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKey2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResultFolder2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResultFolder2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear2)
                    .addComponent(btnStart2))
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("Folder", folderPanel);

        checkPanel.setBackground(new java.awt.Color(33, 120, 255));
        checkPanel.setForeground(new java.awt.Color(255, 255, 255));

        btnClear3.setBackground(new java.awt.Color(29, 155, 236));
        btnClear3.setForeground(new java.awt.Color(255, 255, 255));
        btnClear3.setText("CLEAR");
        btnClear3.setToolTipText("");
        btnClear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear3ActionPerformed(evt);
            }
        });

        btnStart3.setBackground(new java.awt.Color(29, 155, 236));
        btnStart3.setForeground(new java.awt.Color(255, 255, 255));
        btnStart3.setText("START");
        btnStart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart3ActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Original file");

        txtOriginalFilePath.setBackground(new java.awt.Color(143, 218, 238));
        txtOriginalFilePath.setMaximumSize(new java.awt.Dimension(234, 27));
        txtOriginalFilePath.setMinimumSize(new java.awt.Dimension(234, 27));
        txtOriginalFilePath.setPreferredSize(new java.awt.Dimension(234, 27));
        txtOriginalFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOriginalFilePathActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Encrypted file");

        txtEncryptedFilePath.setBackground(new java.awt.Color(143, 218, 238));
        txtEncryptedFilePath.setMaximumSize(new java.awt.Dimension(234, 27));
        txtEncryptedFilePath.setMinimumSize(new java.awt.Dimension(234, 27));
        txtEncryptedFilePath.setPreferredSize(new java.awt.Dimension(234, 27));
        txtEncryptedFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEncryptedFilePathActionPerformed(evt);
            }
        });

        btnOriginalFile.setBackground(new java.awt.Color(29, 155, 236));
        btnOriginalFile.setForeground(new java.awt.Color(255, 255, 255));
        btnOriginalFile.setText("+");
        btnOriginalFile.setMaximumSize(new java.awt.Dimension(41, 27));
        btnOriginalFile.setMinimumSize(new java.awt.Dimension(41, 27));
        btnOriginalFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOriginalFileActionPerformed(evt);
            }
        });

        btnEncryptedFile.setBackground(new java.awt.Color(29, 155, 236));
        btnEncryptedFile.setForeground(new java.awt.Color(255, 255, 255));
        btnEncryptedFile.setText("+");
        btnEncryptedFile.setMaximumSize(new java.awt.Dimension(41, 27));
        btnEncryptedFile.setMinimumSize(new java.awt.Dimension(41, 27));
        btnEncryptedFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptedFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkPanelLayout = new javax.swing.GroupLayout(checkPanel);
        checkPanel.setLayout(checkPanelLayout);
        checkPanelLayout.setHorizontalGroup(
            checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkPanelLayout.createSequentialGroup()
                .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(checkPanelLayout.createSequentialGroup()
                                .addComponent(txtEncryptedFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEncryptedFile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(checkPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(checkPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnClear3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStart3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(checkPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(checkPanelLayout.createSequentialGroup()
                        .addComponent(txtOriginalFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOriginalFile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        checkPanelLayout.setVerticalGroup(
            checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOriginalFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOriginalFile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEncryptedFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEncryptedFile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear3)
                    .addComponent(btnStart3))
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("Check integrity", checkPanel);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Folder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear2ActionPerformed
        jProgressBar1.setIndeterminate(false);
        jProgressBar1.setValue(0);
    }//GEN-LAST:event_btnClear2ActionPerformed

    private void radioEncrypt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEncrypt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEncrypt2ActionPerformed

    private void radioDecrypt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDecrypt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDecrypt2ActionPerformed

    private void txtFilePath2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilePath2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilePath2ActionPerformed

    private void txtKeyPath2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeyPath2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeyPath2ActionPerformed

    private void txtResultFolder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultFolder2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultFolder2ActionPerformed

    private void btnClear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear3ActionPerformed
        jProgressBar1.setIndeterminate(false);
        jProgressBar1.setValue(0);
    }//GEN-LAST:event_btnClear3ActionPerformed

    private void txtOriginalFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOriginalFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOriginalFilePathActionPerformed

    private void txtEncryptedFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEncryptedFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEncryptedFilePathActionPerformed

    private void btnFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFile1ActionPerformed
        boolean hasSet = !"".equals(txtFilePath1.getText());
        chooseFile.showOpenDialog(null);
        try {
            inputFile = chooseFile.getSelectedFile();
            inputFilePath = inputFile.getPath();
            txtFilePath1.setText(inputFilePath);
            //Done 15% progress
            //if (!hasSet) jProgressBar1.setValue(jProgressBar1.getValue()+15);
	} 
        catch (NullPointerException e) {
            txtFilePath1.setText("No file selected");
        }
    }//GEN-LAST:event_btnFile1ActionPerformed

    private void txtResultFolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultFolder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultFolder1ActionPerformed

    private void txtKeyPath1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeyPath1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeyPath1ActionPerformed

    private void txtFilePath1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilePath1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilePath1ActionPerformed

    private void radioDecrypt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDecrypt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDecrypt1ActionPerformed

    private void radioEncrypt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEncrypt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEncrypt1ActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        jProgressBar1.setIndeterminate(false);
        jProgressBar1.setValue(0);
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnKey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKey1ActionPerformed
        chooseFile.showOpenDialog(null);
        try {
            key = chooseFile.getSelectedFile();
            keyPath = key.getPath();
            txtKeyPath1.setText(keyPath);
        //Done 15% progress
        //jProgressBar1.setValue(jProgressBar1.getValue()+15);
        }
        catch(NullPointerException e) {
            txtKeyPath1.setText("No key selected");
        }
    }//GEN-LAST:event_btnKey1ActionPerformed

    private void btnResultFolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultFolder1ActionPerformed
        chooseDirectory.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooseDirectory.showOpenDialog(null);
        try {
            resultFolder = chooseDirectory.getSelectedFile();
            resultFolderPath = resultFolder.getPath();
            txtResultFolder1.setText(resultFolderPath);
        //Done 15% progress
        //jProgressBar1.setValue(jProgressBar1.getValue()+15);
        }
        catch (NullPointerException e) { 
            txtResultFolder1.setText("No folder selected");
        }
    }//GEN-LAST:event_btnResultFolder1ActionPerformed

    private void btnFile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFile2ActionPerformed
        chooseDirectory.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooseDirectory.showOpenDialog(null);
        try {
            inputFile = chooseDirectory.getSelectedFile();
            inputFilePath = inputFile.getPath();
            txtFilePath2.setText(inputFilePath);
        } 
        catch (NullPointerException e) {
            txtFilePath2.setText("No folder selected");
        }
    }//GEN-LAST:event_btnFile2ActionPerformed

    private void btnKey2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKey2ActionPerformed
        chooseFile.showOpenDialog(null);
        try {
            key = chooseFile.getSelectedFile();
            keyPath = key.getPath();
            txtKeyPath2.setText(keyPath);
        } 
        catch (NullPointerException e) {
            txtKeyPath2.setText("No key selected");
        }
    }//GEN-LAST:event_btnKey2ActionPerformed

    private void btnResultFolder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultFolder2ActionPerformed
        chooseDirectory.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooseDirectory.showOpenDialog(null);
        try {
            resultFolder = chooseDirectory.getSelectedFile();
            resultFolderPath = resultFolder.getPath();
            txtResultFolder2.setText(resultFolderPath);
        } 
        catch (NullPointerException e) {
            txtResultFolder2.setText("No folder selected");
        }
    }//GEN-LAST:event_btnResultFolder2ActionPerformed

    private void btnOriginalFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOriginalFileActionPerformed
        chooseFile.showOpenDialog(null);
        try {
            inputFile = chooseFile.getSelectedFile();
            inputFilePath = inputFile.getPath();
            txtOriginalFilePath.setText(inputFilePath);
        } 
        catch (NullPointerException e) {
            txtOriginalFilePath.setText("No file selected");
        }
    }//GEN-LAST:event_btnOriginalFileActionPerformed

    private void btnEncryptedFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptedFileActionPerformed
        chooseFile.showOpenDialog(null);
        try {
            encryptedFile = chooseFile.getSelectedFile();
            encryptedFilePath = encryptedFile.getPath();
            txtEncryptedFilePath.setText(encryptedFilePath);
        } 
        catch (NullPointerException e) {
            txtEncryptedFilePath.setText("No file selected");
        }
    }//GEN-LAST:event_btnEncryptedFileActionPerformed

    private void btnStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart1ActionPerformed
        // TODO add your handling code here:
        //Done 50% progress
        jProgressBar1.setIndeterminate(true);
        //Get some informations about algorithm, key and file
        String algorithm = comboCryptType1.getSelectedItem().toString();
        String filePath = txtFilePath1.getText();
        String keyPath = txtKeyPath1.getText();
        String resultFolderPath = txtResultFolder1.getText();
        String key = "";
        //Read input file
        try {
            if ("".equals(filePath)) throw new Exception();
            inputFile = new File(filePath);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(frame, "Can't read input file.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        //Done 60% progress
        //jProgressBar1.setValue(jProgressBar1.getValue()+10);
        //Read key file
        try {  
            key = new Scanner(new File(keyPath)).useDelimiter("\\Z").next();
        } catch(FileNotFoundException e) {
            JOptionPane.showMessageDialog(frame, "Can't read key file.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        //Done 70% progress
        //jProgressBar1.setValue(jProgressBar1.getValue()+10);
        //Make output file
        try {
            encryptedFile = new File(resultFolderPath+"\\"+inputFile.getName()+".encrypted");
            decryptedFile = new File(resultFolderPath+"\\"+inputFile.getName()+".decrypted");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(frame, "Invalid result folder path.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        //Done 80% progress
        //jProgressBar1.setValue(jProgressBar1.getValue()+10);
        //Do encrypt/decrypt
        if (radioEncrypt1.isSelected() && "DES".equals(algorithm)) try {
            DES.encrypt(key, inputFile, encryptedFile);
        } catch (CryptoException | NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | InvalidKeySpecException ex) {
            Logger.getLogger(Frame1.class.getName()).log(Level.SEVERE, null, ex);
        } 
        else if (radioDecrypt1.isSelected() && "DES".equals(algorithm)) try {
            DES.decrypt(key, inputFile, decryptedFile);
        } catch (CryptoException | NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | InvalidKeySpecException ex) {
            Logger.getLogger(Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Finish 100% progress
        //jProgressBar1.setValue(jProgressBar1.getValue()+20);
    }//GEN-LAST:event_btnStart1ActionPerformed

    private void comboCryptType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCryptType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCryptType1ActionPerformed

    private void btnStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart2ActionPerformed
        jProgressBar1.setIndeterminate(true);
    }//GEN-LAST:event_btnStart2ActionPerformed

    private void btnStart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart3ActionPerformed
        jProgressBar1.setIndeterminate(true);
    }//GEN-LAST:event_btnStart3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frame1 frame = new Frame1();
                frame.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnClear3;
    private javax.swing.JButton btnEncryptedFile;
    private javax.swing.JButton btnFile1;
    private javax.swing.JButton btnFile2;
    private javax.swing.JButton btnKey1;
    private javax.swing.JButton btnKey2;
    private javax.swing.JButton btnOriginalFile;
    private javax.swing.JButton btnResultFolder1;
    private javax.swing.JButton btnResultFolder2;
    private javax.swing.JButton btnStart1;
    private javax.swing.JButton btnStart2;
    private javax.swing.JButton btnStart3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel checkPanel;
    private javax.swing.JComboBox<String> comboCryptType1;
    private javax.swing.JComboBox<String> comboCryptType2;
    private javax.swing.JPanel filePanel;
    private javax.swing.JPanel folderPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton radioDecrypt1;
    private javax.swing.JRadioButton radioDecrypt2;
    private javax.swing.JRadioButton radioEncrypt1;
    private javax.swing.JRadioButton radioEncrypt2;
    private javax.swing.JTextField txtEncryptedFilePath;
    private javax.swing.JTextField txtFilePath1;
    private javax.swing.JTextField txtFilePath2;
    private javax.swing.JTextField txtKeyPath1;
    private javax.swing.JTextField txtKeyPath2;
    private javax.swing.JTextField txtOriginalFilePath;
    private javax.swing.JTextField txtResultFolder1;
    private javax.swing.JTextField txtResultFolder2;
    // End of variables declaration//GEN-END:variables
}
